### ISSUE TITLE
Login with Google redirects to localhost

### ISSUE THREAD

**Issue by e5pe** [Luzefiru/wuwatracker#146] opened 2024-09-18 06:57 UTC
# Bug Description

I signed in with my google account and it redirected to a localhost:3000 url, so I guess that is not right.
I clicked on the user icon, on the top right, then in the Sign In To Google button 
## How to Reproduce

_A reproduction repository is greatly appreciated._

1. Go to any part of the application
2. Click on the user icon on the top right
3. Go to the part down of the menu
4. Click on "Sign In To Google"
5. Do the authentication with Google
7. See error and that it redirects to "http://localhost:3000/?code=some_uuid" I guess the last part is an uuid, but if you need the one that I saw I would send to you :)

## Expected Behavior

The expected behaviour would be redirected to the website wuwatracker with and user logged in.

## Screenshots

![image](https://github.com/user-attachments/assets/8f94d4e3-cbb7-49fc-a4aa-2ee949ea2563)

## Platform/OS

- OS: PC
- Browser vivaldi
- Version 6.9.3447.44

## Additional Context

Please let me know if your need more information. Thank you!

**Comment by Luzefiru** [comment] 2024-09-18 07:01
Thanks for raising the issue, @e5pe! We'll look into this as soon as possible.

**Comment by Luzefiru** [comment] 2024-09-18 07:16
Could you please try refreshing the page & logging in again? It should work now if our assumptions are correct.

And were you able to successfully login in via another browser or in "Incognito" mode?

**Comment by Luzefiru** [comment] 2024-09-19 02:07
@e5pe, I'm unable to reproduce the issue on my PC with Vivaldi 6.9.3447.44. Do you have any browser extensions installed by any chance? If so, could you enumerate what they are?

**Comment by e5pe** [comment] 2024-09-19 05:01
Hello @Luzefiru I found the extension that caused trouble, was this one: https://chromewebstore.google.com/detail/malwarebytes-browser-guar/ihcjicgdanjaechkgeegckofjjedodee
Malwarebytes Browser Guard

Because I tried on firefox and I had the same issue, because I use the same extension there too haha

I had to disable the Ads / Trackers protection on the wuwa tracker website, then the login worked

**Comment by Luzefiru** [comment] 2024-09-19 07:09
> Hello @Luzefiru I found the extension that caused trouble, was this one: https://chromewebstore.google.com/detail/malwarebytes-browser-guar/ihcjicgdanjaechkgeegckofjjedodee Malwarebytes Browser Guard
> 
> Because I tried on firefox and I had the same issue, because I use the same extension there too haha
> 
> I had to disable the Ads / Trackers protection on the wuwa tracker website, then the login worked

Oh I see. Thank you for pointing that out and updating us! We'll use this as reference for similar issues in the future.

I'll be closing this issue now. 👍

**Closed by Luzefiru** 2024-09-19 07:09 UTC
Labels: bug
